name: Create and publish a Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-to-ghcr:
    uses: syginc/actions-util/.github/workflows/ghcr-publish.yml@master
    with:
      image_name: ${{ github.repository }}
      tag: latest
      file_path: latest/Dockerfile
      context_path: .
    secrets:
      registry_username: ${{github.actor}}
      registry_password: ${{secrets.GITHUB_TOKEN}}
